### PR TITLE
fix permission between nginx and php-fpm

### PR DESCRIPTION
**Pull request by adriy-be**
I have got "403 Forbidden" error with a webdav mount. Change the user id to resolve the problem.
Inspired by https://stackoverflow.com/questions/36120679/wrong-permissions-in-volume-in-docker-container/36130772#36130772

### CODE REVIEW

**Comment by adriy-be** [comment]
Do not approve, I have do 💩. I have retry my fix, and now I have a white page.
It's late and I'm tired. I verify that tomorow when I have free time.

**Comment by secure-77** [comment]
The problem is not between the nginx and php container, nginx will communicate via the socket to the php-fpm container. Nginx only "loads and serves" the php files to the php engine, the php engine then loads the markdown files, this is the reason why the nginx container don't need to have you notes volume. The problem what you have is probably between your local user and the user of the php container. But if you set your local vault folder to world readable the php engine should be able to load the files, we can check this further in discord if you want but I don't think that a permission change in the docker containers is necessary

**Comment by adriy-be** [comment]
> The problem is not between the nginx and php container, nginx will communicate via the socket to the php-fpm container. Nginx only "loads and serves" the php files to the php engine, the php engine then loads the markdown files, this is the reason why the nginx container don't need to have you notes volume. The problem what you have is probably between your local user and the user of the php container. But if you set your local vault folder to world readable the php engine should be able to load the files, we can check this further in discord if you want but I don't think that a permission change in the docker containers is necessary

So When I tried you demo, that worked fine. When I mount a web-dav directory and when I have picture inside this webdav, I have a 403 error.

You can see my branch web-dav : https://github.com/adriy-be/Perlite/tree/WebDav
With that, I don't have the error.

The white page is just due to I have put an "_" at the nginx config mount point 🙄

So, thanks for your reply. Have a good night 😴

**Comment by secure-77** [comment]
Well, what I wrote was wrong, the nginx container indeed need also the vault volume, I just overlooked the
```volumes_from: 
      - perlite     
```
in the docker compose file.

However I checked again some permissions. 

- The php-fpm deamon runs as the user id 82 (which is the user www-data in the container)
- The nginx deamon runs as the user id 101 (which is the nginx user in the container)
- The vault (volume) gets mounted to the containers with the permissions it has on your local host


However if the vault folder and all files have the a+r and a+x flag, the user of the container should not matter and it should work without any changes. Take care that the vault folder (and content) musst be world readable *AND* world executable.  The reason why it is working for you after changing the php user to id 101 is probably because you have this id / user as owner or group set to your vault in your host.

So im pretty sure the user id change to 101 is not necessary when your vault folder has the necessary permissions :)

**Comment by ovxrfl0w** [comment]
Instead of relying on vault folder permissions from the host how about mounting the vault directory and copying the contents from that directory to a directory inside of the container and changing permissions there? This would solve this issue while also not interfering with directory permissions on the host system needlessly.

**Comment by secure-77** [comment]
> Instead of relying on vault folder permissions from the host how about mounting the vault directory and copying the contents from that directory to a directory inside of the container and changing permissions there? This would solve this issue while also not interfering with directory permissions on the host system needlessly.

true, the alternative way would be to use docker volumes, but then you always need to restart docker compose to get the content copied to the docker volume. Also there are vaults which are gigabytes of data, which will take time to copy and also take disc space. 

There is also a way to set the user ids of the container to the current user for example via an .env file but this is also not optimal and needs to be adjusted for every system. However, if setting the permissions is really a problem then I would go this way and manually change the ids for the php-fpm and nginx service in the containers to someone who has permissions to the vault

**Pull request closed without merging**
