### PR TITLE
feat: support external obsidian links

### PR DESCRIPTION
**Pull request by Tooa**
Hi :wave:,

this pull request remodels the link in the upper right corner as external obsidian link. This allows opening and editing your notes in Obsidian right away. 

Leaving the pull request as draft for now, as I would like to have some input.

- Unsure, if replacing the href attribute breaks another feature. I couldn't find how the link is useful other than opening the same site I already have open
- I use an Id attribute and `getElementById` to retrieve the vault name in the JavaScript part. Maybe there is a better solution
- The link only works when `NOTES_PATH` represents the Obsidian vault name. It does not work when a user does not use this variable and hosts the markdown files in the root folder. Maybe we should decouple the vault name from the `NOTES_PATH` and introduce another environment variable

**docker-compose.yml**
```yaml
services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite-dev
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash
    volumes:
      - ./perlite:/var/www/perlite
      - ./Demo:/var/www/perlite/Demo:ro
[...]
```

Let me know if you want something changed.

### CODE REVIEW

**Comment by secure-77** [comment]
Hey @Tooa,

Thanks for this great idea. The link in the upper right corner was introduced before the URL update in the Browser bar, so in the past it was the only way to share are note via direct link. Now its more like breadcrumps and the idea putting more functionally behind it is great.

I see one problem related to the this. Perlite is meant to share your notes with the world, so expect the owner of the vault, nobody else can use this link and clicking on it will raise some errors or at least confusion.

But the idea is still great. Maybe we can introduce an "edit" button next to the link and maybe via a cookie / button we can toggle the display of this button. 

What do you think?

**Comment by Tooa** [comment]
> Hey @Tooa,
> 
> Thanks for this great idea. The link in the upper right corner was introduced before the URL update in the Browser bar, so in the past it was the only way to share are note via direct link. Now its more like breadcrumbs and the idea putting more functionally behind it is great.
> 
> I see one problem related to this. Perlite is meant to share your notes with the world, so expect the owner of the vault, nobody else can use this link and clicking on it will raise some errors or at least confusion.
> 
> But the idea is still great. Maybe we can introduce an "edit" button next to the link and maybe via a cookie / button we can toggle the display of this button.
> 
> What do you think?

I added your feedback with my latest commits. I kind of dislike the coupling between `NOTES_PATH` and the vault name as it breaks the feature when a user hosts the files in the web root directory. But, adding another environment variable just for this feature feels overkill. 

Let me know what you think.

**Comment by secure-77** [comment]
Very nice feature, love it! Thank you very much @Tooa

**Comment by Tooa** [comment]
Thank you for your kind words and resolving the open tasks @secure-77. I like your idea for storing the vault name in the cookie.

**Pull request merged**
